services:
  app:
    build: .
    container_name: codeigniter_app
    volumes:
      - ./:/var/www/html
    ports:
      - "8081:80"
    depends_on:
      - db
    environment:
      - TZ=America/Sao_Paulo
  db:
    image: mysql:5.7
    container_name: codeigniter_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: controle_pedidos
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
      TZ: America/Sao_Paulo
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: 